name: Add Labels

on:
  pull_request:
    branches: 
      - master

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: "${{secrets.GITHUB_TOKEN}}"
          configuration-path: .github/labeler.yml
